services:
  - type: web
    name: react-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://your-fastapi-app-name.onrender.com